[general]
import = ["~/.config/alacritty/themes/dracula.toml"]

[env]
TERM = "xterm-256color"

[terminal]
shell = "zellij"

[window]
dimensions.columns = 90
dimensions.lines = 30
padding.x = 6
padding.y = 4
#decorations = "None"
opacity = 0.98

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 12

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
